version: '2'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: luontola/sync-k8s-nodes-to-gcp-dns
    environment:
      DNS_NAMES: k8s-test1.luontola.fi. k8s-test2.luontola.fi. k8s-test3.luontola.fi.
      GOOGLE_PROJECT: www-prod-204113
      GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/gcp-keys.json
    volumes:
    - ../www-prod-dns-admin-keys.json:/var/secrets/gcp-keys.json:ro
